### ISSUE TITLE
Site tutorials and examples do not match code in repo

### ISSUE THREAD

**Issue by matsbror** [wasmCloud/wasmcloud-dev-site#21]
I am following the tutorials for new actors and there are several places where the site does not match the code. I will fork and try to make a PR out of this.

**Comment by brooksmtownsend** [comment]
Hey @matsbror, would you mind pointing out any places that you still see outdated? I tried to skim through and address anything I saw in #29

**Comment by matsbror** [comment]
Sure, I got distracted and could not finish this work, but it's time for me to go at it again.

**Comment by matsbror** [comment]
@brooksmtownsend found another place, now in https://wasmcloud.dev/app-dev/create-provider/rust/
where the code example uses dashes instead of underscore:
`extern crate wasmcloud-provider-core as codec;`

**Comment by stevelr** [comment]
This should be addressed by https://github.com/wasmCloud/wasmcloud-dev-site/issues/52

**Comment by autodidaddict** [comment]
if this is a dupe being addressed by another issue we should close this.
