### ISSUE TITLE
UI Bug: copy button is added to code tags

### ISSUE THREAD

**Issue by snnsnn** [wasmCloud/wasmcloud-dev-site#24]
Ui ads `<span class="copy-to-clipboard">copy</span>` element to `<code>` tags when navigating via links (usually one but sometimes more than one) and these buttons get multiplied when using forward and backward buttons and eventually page becomes unresponsive.

It happens in Firefox 86.0 (64-bit) and Chromium Version 89.0.4389.90 (Official Build) snap (64-bit).

Here is an image and screen captures. At the end of the second video, you can see console log. I also added parts of it below:

![wasmcloud-console](https://user-images.githubusercontent.com/16473630/111339679-035cff80-8689-11eb-8492-7e52fd6ef2b2.png)

https://user-images.githubusercontent.com/16473630/111343843-df9bb880-868c-11eb-8ee7-8c9d041e48aa.mp4

https://user-images.githubusercontent.com/16473630/111339513-df012300-8688-11eb-9986-bf58a7b0f598.mp4

```
DevTools failed to load SourceMap: Could not load content for https://wasmcloud.dev/plugins/bootstrap/bootstrap.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
```
You are loading Turbolinks from a <script> element inside the <body> element. This is probably not what you meant to do!

Load your application’s JavaScript bundle inside the <head> element instead. <script> elements in <body> are evaluated with each page change.

For more information, see: https://github.com/turbolinks/turbolinks#working-with-script-elements

——
Suppress this warning by adding a `data-turbolinks-suppress-warning` attribute to: <script src="https://wasmcloud.dev/plugins/turbolinks/turbolinks.js"></script>
(anonymous) @ turbolinks.js:6
(anonymous) @ turbolinks.js:6
(anonymous) @ turbolinks.js:6
(anonymous) @ turbolinks.js:6
(anonymous) @ turbolinks.js:6
```

**Comment by autodidaddict** [comment]
We've seen this since we started using this template, sadly. Currently the fix is to just hit refresh and all the copy spam goes away, but we really need to fix the CSS/JS in the template so this doesn't happen. Pinging @brooksmtownsend or @ChrisRx in case they might be able to look into/troubleshoot the CSS/JS problem.
