### ISSUE TITLE
Update create provider section

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-dev-site#48]
In the create provider section: https://wasmcloud.dev/app-dev/create-provider/, there are some outdated references to widl files, interfaces, and no mention of https://github.com/wasmCloud/new-provider-template which should be the de-facto way to create a rust provider.

**Comment by stevelr** [comment]
This will be fixed as part of https://github.com/wasmCloud/wasmcloud-dev-site/issues/52 - setting points to zero.
