### ISSUE TITLE
Live update / local registry needs

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-dev-site#68]
1. WASMCLOUD_OCI_ALLOWED_INSECURE needs to be set in order for the user to actually start actors/providers from the local registry
2. The `make update` command either needs to be commented back in for the common makefile, or we need to provide a live update command that can be run manually. I'd lean towards the former, as we should provide the `make update` functionality

We could potentially mitigate `1` if we can find a way to serve the localhost registry over https, but that would only be worth it if we can easily provide that as a part of the docker compose, not worth it if multiple certificates are required.

**Comment by stevelr** [comment]
Closing as a dup of https://github.com/wasmCloud/wash/issues/193
