### ISSUE TITLE
Getting started section needs to be completed

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-dev-site#8]
This is the section of the docs right beneath "installation", and this is in most cases going to be a developer's first exposure to wasmCloud. This section of the docs should walk the developer through their first experience with `wash` by having them fire up the repl and go through the simple demo script - start an actor, start a provider, link the actor to the provider, curl the endpoint, and then finish up with a taste for advanced techniques by doing a direct call on the actor.

**Comment by brooksmtownsend** [comment]
My brainstormed flow for this is:

1. Get them to run NATS
2. run `wash up` to enter REPL & launch a host
3. run `help`, `get hosts` to show the running host, and `get inventory NDASJDKHASJKDH` to show the resources currently running
4. `ctl start actor wasmcloud.azurecr.io/echo:0.1.0`
5. `ctl start provider wasmcloud.azurecr.io/httpserver:0.10.0`
6. `ctl get inventory NDASDASD` to show running resources
6. `ctl link ECHOPKEY PROVIDERPKEY wasmcloud:httpserver PORT=8080`
7. `curl localhost:8080`
8. `ctl call ECHOPKEY HandleRequest {payload_here}`

**Comment by brooksmtownsend** [comment]
Thoughts on including screenshots of REPL at some stages of this tutorial @autodidaddict?

**Comment by brooksmtownsend** [comment]
This was closed by #10
